### ISSUE TITLE
Emergency 4 SDK?

### ISSUE THREAD

**Issue by Nexuist** [digital195/emergency5_sdk_doc#1]
Hi,

Thank you for your hard work with this documentation. I was wondering if you have any idea where I can find the Emergency 4 SDK / documentation. All of the previous links on emergency-planet and elsewhere have died over the years including the emergency-wiki link that everyone seems to point to. Given that this repo is for active modders, I was wondering if anyone knows where I can find the SDK and if it may be possible to add it to this repo? If someone can direct me to the SDK I can prepare a pull request to merge it into this main branch myself.

Thank you,
Andi

**Comment by digital195** [comment]
Hey,

you can find the emergency 4 sdk on the new german forum.  

[https://em-hub.de/](https://em-hub.de/)

[https://em-hub.de/lexicon/lexicon/38-sdk/](https://em-hub.de/lexicon/lexicon/38-sdk/)
